name: Build and test
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          verb: call
          args: build --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
