name: Publish the application to ttl.sh
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          verb: call
          args: publish --source=. --image-name=ttl.sh/echo-server-$RANDOM:1h
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
